name: 로컬 엔진 빌드

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.41.4
  FLUTTER_CHANNEL: stable
  PATCH_FILE: diff.patch

jobs:
  build-local-engine:
    name: 로컬 엔진 빌드
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v6

      - name: 릴리즈에 어셋 업로드 테스트
        run: |
          echo "GITHUB_REF:        ${{ github.ref }}"
          echo "GITHUB_REF_NAME:   ${{ github.ref_name }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"

          # 현재 gh가 바라보는 repo
          git remote -v
          gh release list --limit 20

          if ! gh release view "${{ github.ref_name }}" --repo "${{ github.repository }}" >/dev/null 2>&1; then
            echo "릴리스(${{ github.ref_name }})가 ${{ github.repository }}에 없습니다. 릴리스 먼저 생성됐는지 확인해주세요."
            exit 1
          fi

          echo "릴리스(${{ github.ref_name }})가 ${{ github.repository }}에 있습니다."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 환경 변수 설정
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            CACHE_KEY="${{ github.base_ref }}"
          else
            CACHE_KEY="${{ github.ref_name }}"
          fi
          echo "CACHE_KEY=$CACHE_KEY" >> $GITHUB_ENV
          echo "FLUTTER_KEY=flutter-sdk-${{ runner.os }}-${{ env.FLUTTER_VERSION }}-${{ runner.arch }}-${{ env.FLUTTER_CHANNEL }}" >> $GITHUB_ENV
          echo "PUB_CACHE_KEY=pub-cache-${CACHE_KEY}-${{ runner.os }}-${{ env.FLUTTER_VERSION }}-${{ runner.arch }}-${{ env.FLUTTER_CHANNEL }}" >> $GITHUB_ENV

      - name: depot_tools 설치
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: 로컬 엔진 빌드
        run: bash build-local-engine.sh ${{ env.FLUTTER_VERSION }} ${{ env.FLUTTER_CHANNEL }} ${{ env.PATCH_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Flutter SDK 캐시 구성
        uses: actions/cache@v5
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ env.FLUTTER_KEY }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: pub dependencies 캐시 구성
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/flutter/pub-cache
          key: ${{ env.PUB_CACHE_KEY }}
